Feat friends backup
Barresi/sakura-back pull request #7
Opened 2023-09-25 09:11 UTC by qSatan1s

2023-09-28 13:53 UTC, Winter4 reviewed
Общее по проекту - от `console.method()` нужно избавиться, для этого есть логгер. Можно в еслинт добавить запрет на консоль логи

2023-09-28 13:53 UTC, Winter4 commented on .eslintrc
> +{
Можно кратко словами, на что настроен еслинт и на что будет ругаться ?

2023-09-28 13:53 UTC, Winter4 commented on .husky/pre-commit
> -npx prettier --write source/
1. Переместить `npx tsc` в `pre-push` можно, согласен в целом
2. Выкинуть `prettier` из `pre-commit` - обоснуй

2023-09-28 13:53 UTC, Winter4 commented on .idea/.gitignore
IDE-specific папка (вебшторм же?)
Нужна она здесь? В гитигнор бы

2023-09-28 13:53 UTC, Winter4 commented on README.md
> +> swagger docs:  [link]/api/v1/api-docs/
`/api/v1/v1-docs` ?
`/api/v1/api-v1-docs` ?

2023-09-28 13:53 UTC, Winter4 commented on package.json
> +    "lint": "eslint \"./**/*.ts\" --quiet --fix"
1. Можно закинуть в гит хуки (препуш?)
2. Разделить бы `--fix` и просто линт

2023-09-28 13:53 UTC, Winter4 commented on source/api/async-wrapper.ts
В чём замысел? В логах так или иначе будет мета-дата по запросу, который вызвал ошибку

2023-09-28 13:53 UTC, Winter4 commented on source/api/router.ts
> +api.use('/v1', v1);
Почему? :)

upd: линтер ?

2023-09-28 13:53 UTC, Winter4 commented on source/api/v1/friends/friends.controller.ts
> +      return res.status(400).json({ error: 'Пользователь с friendId не найден' });
"Такой пользователь не найден"

2023-09-28 13:53 UTC, Winter4 commented on source/data/friends.ts
> +const db = new PrismaClient();
Инстанс забирается с синглтон-объекта

2023-09-28 13:53 UTC, Winter4 commented on source/api/v1/swaggerDef.ts
> +import swaggerJsdoc from 'swagger-jsdoc';
`swaggerJSDoc` ?

2023-09-28 13:53 UTC, Winter4 commented on source/api/v1/swaggerDef.ts
`swaggerDef.ts` -> `v1.swagger.ts` / `swagger.ts`

2023-09-28 13:53 UTC, Winter4 commented on source/api/v1/friends/friends.router.ts
Отступов можно вдвое меньше :)

2023-09-28 13:53 UTC, Winter4 commented on source/api/v1/friends/friends.router.ts
> +friend.post('/add-friend', [authJwt.verifyToken], addFriend);
зачем оборачивать в массив ?

2023-09-28 13:53 UTC, Winter4 commented on source/data/friends.ts
Модель, вероятно, будет немного другой

2023-09-28 13:53 UTC, Winter4 commented on source/api/v1/friends/friends.router.ts
Можно повесить `verifyToken` в `v1.router`

2023-09-30 11:07 UTC, AigulTok commented on source/api/v1/friends/friends.controller.ts
> +    await Friends.acceptFriend(userId, friendId);
У тебя методы перепутаны. removeFriend принимает заявку в друзья

2023-09-30 11:08 UTC, AigulTok commented on source/api/v1/friends/friends.controller.ts
> +    await Friends.removeFriend(userId, friendId);
А здесь наоборот acceptFriend удаляет запрос в друзья

2023-09-30 11:18 UTC, AigulTok commented on source/app.ts
> +  app.listen(port, () => {
Приложение работает на server, а не app. Иначе сокеты не запустятся. api endpoints работают как обычно на server

2023-10-03 09:31 UTC, qSatan1s commented on source/app.ts
> +  app.listen(port, () => {
как оно работает на server ?)
если  
const app = express();
я просто консоль логг сделал который порт выводит, ничего не менял в самом коде

2023-10-03 09:36 UTC, AigulTok commented on source/app.ts
> +  app.listen(port, () => {
const app = express();
const server = http.createServer(app);
server.listen(config.get("deploy.expressPort"));

2023-10-03 09:36 UTC, qSatan1s commented on .idea/.gitignore
у вас гит игнор пустой вообще)) 
туда и .vscode будет утекать

2023-10-03 09:41 UTC, qSatan1s commented on .eslintrc
> +{
airbnb конфиг ругаться будет на плохие практики в Js коде, на не используемый мусор и.т.д

2023-10-03 09:43 UTC, qSatan1s commented on README.md
> +> swagger docs:  [link]/api/v1/api-docs/
у нас версия в роутере прописана, зачем 2 раза v-1 дублировать ?

2023-10-03 09:51 UTC, qSatan1s commented on source/data/friends.ts
почему?

2023-10-03 09:53 UTC, qSatan1s commented on .husky/pre-commit
> -npx prettier --write source/
засунул фикс линтом и добавил pre-push

2023-10-04 06:38 UTC, qSatan1s commented on source/api/v1/swaggerDef.ts
KISS
есть партерновый нейм зачем с ним что-то придумывать)

2023-10-04 17:43 UTC, Winter4 commented on .idea/.gitignore
Ну если бы появилась .vscode, сразу гитигнор был бы дополнен

2023-10-04 17:46 UTC, Winter4 commented on source/api/v1/swaggerDef.ts
Паттерновый, имелось ввиду ?
Можно ссылку на доку, или конвенцию? Не имел удовольствия сетапить сваггер прежде)

2023-10-04 17:46 UTC, Winter4 commented on source/data/friends.ts
Потому что текущая не ок
Не успел выкатить апдейт по этой части

2023-10-04 18:04 UTC, Winter4 requested changes
Общий вопрос - нужна ли нам сотня наворотов и изменение фундамента уже засетапленного проекта?
Такое ощущение что нет

2023-10-04 18:04 UTC, Winter4 commented on create-entity.js
Зачем ?

2023-10-04 21:29 UTC, closed without merging